"use client";
import { useQuery } from "@tanstack/react-query";
import { fetchWeatherPredictions } from "@/lib/api";
import { CloudRain, Wind, Thermometer, Radio, Target } from "lucide-react";
import Link from "next/link";

export default function WeatherPage() {
  const { data: weatherData, isLoading } = useQuery({
    queryKey: ["weather-predictions", 100], queryFn: () => fetchWeatherPredictions(100), refetchInterval: 120_000,
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-extrabold flex items-center gap-3 text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-blue-400">
            <CloudRain className="w-8 h-8 text-sky-400" />
            Weather Intelligence
          </h1>
          <p className="text-gray-400 text-sm mt-2 max-w-xl">
            Live Polymarket weather predictions generated by the Pavlov subsystem. We parse NOAA/NWS data to model temperature highs and wind speeds to calculate market edges.
          </p>
        </div>
        <Link
          href="/trading"
          className="flex items-center gap-2 text-xs font-semibold text-sky-300 hover:text-white bg-sky-950/40 border border-sky-500/30 px-4 py-2.5 rounded-xl transition-all hover:bg-sky-600/40"
        >
          <Target className="w-4 h-4" />
          View Trading Activity
        </Link>
      </div>

      {isLoading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mt-6">
          {[...Array(6)].map((_, i) => (
            <div key={i} className="glass-card h-32 animate-pulse" />
          ))}
        </div>
      ) : (weatherData?.predictions?.length ?? 0) > 0 ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 mt-6">
          {weatherData!.predictions.map((wp) => (
            <div key={wp.id} className="glass-card p-5 border-t-2 border-t-sky-500 hover:shadow-[0_0_20px_rgba(14,165,233,0.15)] transition-shadow">
              <div className="flex items-center gap-2 mb-3">
                {wp.event_key.toLowerCase().includes("temp") ? (
                  <Thermometer className="w-5 h-5 text-sky-400" />
                ) : (
                  <Wind className="w-5 h-5 text-sky-400" />
                )}
                <span className="text-xs text-sky-400 font-semibold tracking-wide uppercase truncate">{wp.event_key}</span>
              </div>
              
              <div className="mb-4">
                <div className="text-xl font-bold text-gray-200">{wp.outcome}</div>
                <div className="text-sm text-gray-400 mt-1">Target Market</div>
              </div>

              <div className="grid grid-cols-3 gap-2 py-3 border-y border-white/5 bg-white/[0.02] -mx-5 px-5">
                <div>
                  <div className="text-[10px] text-gray-500 uppercase">Model</div>
                  <div className="font-bold text-sky-300">{Math.round(wp.prob * 100)}%</div>
                </div>
                <div className="border-l border-white/5 pl-3">
                  <div className="text-[10px] text-gray-500 uppercase">Market</div>
                  <div className="font-bold text-gray-300">{Math.round((wp.market_price || 0) * 100)}%</div>
                </div>
                <div className="border-l border-white/5 pl-3">
                  <div className="text-[10px] text-gray-500 uppercase">Edge</div>
                  <div className={`font-bold ${wp.edge && wp.edge >= 0.05 ? "text-emerald-400" : "text-gray-400"}`}>
                    {wp.edge != null ? `+${(wp.edge * 100).toFixed(1)}%` : "—"}
                  </div>
                </div>
              </div>

              <div className="mt-4 flex items-center justify-between text-xs">
                <span className="text-gray-500">
                  {new Date(wp.created_at).toLocaleDateString()} {new Date(wp.created_at).toLocaleTimeString([], {hour: '2-digit', minute: '2-digit'})}
                </span>
                {wp.edge && wp.edge >= 0.05 && (
                  <span className="px-2 py-0.5 bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded text-[10px] uppercase font-bold">
                    Actionable
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div className="glass-card py-20 flex flex-col items-center justify-center text-gray-500 mt-6">
          <Radio className="w-12 h-12 mb-4 opacity-20" />
          <p className="text-lg">No weather predictions generated recently.</p>
          <p className="text-sm mt-2 max-w-md text-center">The Pavlov subsystem wakes up on a schedule to analyze NOAA data and generate predictions.</p>
        </div>
      )}
    </div>
  );
}
